credentials:
  usernames:
    valiant:
      email: idmoh44@yahoo.com
      name: Mohammed Idris
      password: '456123'  # This should be a hashed password
cookie:
  expiry_days: 0
  key: cookie_signature_key
  name: cookie_name
preauthorized:
  usernames:
  - beela