credentials:
  usernames:
    analystidris:
      email: idmoh44@yahoo.com
      logged_in: False
      name: Mohammed Idris
      password: '456123'  # This should be a hashed password
cookie:
  expiry_days: 0
  key: cookie_signature_key
  name: cookie_name
preauthorized:
  emails:
  - mohammed.idris@azubiafrica.org
usernames:
  